api_platform:
    title: 'Budget Application'
    description: 'API description'
    version: '2.0.0'
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    swagger:
        versions: [ 3 ]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    openapi:
        contact:
            name: Den Rolya
            email: denrolya@gmail.com
