api_platform:
    title: 'Budget Application'
    description: 'API description'
    version: '2.0.0'
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    openapi:
        contact:
            name: Den Rolya
            email: denrolya@gmail.com

    defaults:
        pagination_client_items_per_page: true
    collection:
        pagination:
            items_per_page_parameter_name: perPage # Default value
