api_platform:
    title: 'Budget Application'
    description: 'API description'
    version: '2.0.0'
    show_webby: false
    # Allow using plain IDs for JSON format.
    allow_plain_identifiers: true
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    swagger:
        versions: [ 3 ]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    openapi:
        contact:
            name: Den Rolya
            email: denrolya@gmail.com

    defaults:
        pagination_client_items_per_page: true
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    collection:
        pagination:
            items_per_page_parameter_name: perPage # Default value
    http_cache:
        invalidation:
            enabled: true
        public: true

