# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    http_cache:
        enabled: true

    messenger:
        transports:
            sync: 'sync://'
        routing:
            'App\Message\UpdateAccountLogsOnTransactionCreateMessage': sync
            'App\Message\UpdateAccountLogsOnTransactionUpdateMessage': sync
            'App\Message\UpdateAccountLogsOnTransactionRemoveMessage': sync

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    http_client:
        scoped_clients:
            fixer_client:
                base_uri: '%env(FIXER_BASE_URL)%'
                headers:
                    apiKey: '%env(FIXER_API_KEY)%'
            wise_client:
                base_uri: '%env(WISE_BASE_URL)%'
                headers:
                    Authorization: 'Bearer %env(WISE_API_KEY)%'
            monobank_client:
                base_uri: '%env(MONOBANK_BASE_URL)%'
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
