version: "3"
services:
    sonarqube:
        image: sonarqube:community
        container_name: sonarqube
        ports:
            - "9000:9000"
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://db/sonarqube
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
        depends_on:
            - db

    db:
        image: postgres
        container_name: sonarqube-postgres
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
            POSTGRES_DB: sonarqube
        ports:
            - "5432:5432"
