<?php

declare(strict_types=1);

namespace App\DataFixtures\Dev;

use App\Entity\Budget;
use App\Entity\BudgetLine;
use App\Entity\Category;
use App\Entity\ExpenseCategory;
use App\Entity\IncomeCategory;
use App\Entity\User;
use Carbon\CarbonImmutable;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

/**
 * Creates a realistic set of budgets for development:
 *
 *  - Current month:  active budget using root-category lines; planned ~€4 300 total
 *                    expense, should land B/C grade with partial-month actuals
 *  - Previous month: generous plan (€4 500 expense) → completed A grade
 *  - Two months ago: generous plan (€4 080 expense) → completed A grade
 *  - Current year:   yearly EUR budget with all root categories → A grade
 *  - Q1 custom:      custom-period EUR budget → A grade
 *  - Empty budget:   edge case — budget with no lines
 *
 * All budgets use root expense categories so every subcategory transaction is
 * covered; amounts are calibrated against the ~€3 300/month generated by
 * ExpenseFixtures across all nine accounts.
 */
class BudgetFixtures extends Fixture implements DependentFixtureInterface
{
    public function load(ObjectManager $manager): void
    {
        $owner = $this->getReference('dev_user', User::class);
        $now = CarbonImmutable::now();

        $expenseRepository = $manager->getRepository(ExpenseCategory::class);
        $incomeRepository = $manager->getRepository(IncomeCategory::class);

        $foodCategory = $expenseRepository->findOneBy(['name' => 'Food & Drinks', 'parent' => null]);
        $housingCategory = $expenseRepository->findOneBy(['name' => 'Housing', 'parent' => null]);
        $transportCategory = $expenseRepository->findOneBy(['name' => 'Transportation', 'parent' => null]);
        $shoppingCategory = $expenseRepository->findOneBy(['name' => 'Shopping', 'parent' => null]);
        $healthCategory = $expenseRepository->findOneBy(['name' => 'Health', 'parent' => null]);
        $otherExpenseCategory = $expenseRepository->findOneBy(['name' => 'Other', 'parent' => null]);

        $salaryCategory = $incomeRepository->findOneBy(['name' => 'Salary', 'parent' => null]);
        $bonusCategory = $incomeRepository->findOneBy(['name' => 'Bonus', 'parent' => null]);
        $rentIncomeCategory = $incomeRepository->findOneBy(['name' => 'Rent', 'parent' => null]);

        // ── Current month: active budget, targets achievable on current pace ────
        $currentMonth = new Budget();
        $currentMonth->setOwner($owner);
        $currentMonth
            ->setPeriodType(Budget::PERIOD_MONTHLY)
            ->setStartDate($now->startOfMonth())
            ->setEndDate($now->endOfMonth())
            ->setName(null);

        // Root-category lines cover all subcategory transactions; amounts set
        // above the ~€3 300 typical monthly actual to produce a healthy score.
        $this->addBudgetLine($currentMonth, $foodCategory, '1400.00', 'EUR', 'All food & drinks');
        $this->addBudgetLine($currentMonth, $housingCategory, '1500.00', 'EUR', 'Rent, utilities, internet');
        $this->addBudgetLine($currentMonth, $transportCategory, '220.00', 'EUR');
        $this->addBudgetLine($currentMonth, $shoppingCategory, '700.00', 'EUR');
        $this->addBudgetLine($currentMonth, $healthCategory, '180.00', 'EUR');
        $this->addBudgetLine($currentMonth, $otherExpenseCategory, '300.00', 'EUR', 'Miscellaneous');
        $this->addBudgetLine($currentMonth, $salaryCategory, '3300.00', 'EUR');
        $manager->persist($currentMonth);

        // ── Previous month: completed successfully — target A grade ─────────────
        $previousMonthStart = $now->subMonths(1)->startOfMonth();
        $previousMonthEnd = $now->subMonths(1)->endOfMonth();

        $previousMonth = new Budget();
        $previousMonth->setOwner($owner);
        $previousMonth
            ->setPeriodType(Budget::PERIOD_MONTHLY)
            ->setStartDate($previousMonthStart)
            ->setEndDate($previousMonthEnd)
            ->setName(null);

        // Generous plan across all roots → actual spending stays well under budget.
        $this->addBudgetLine($previousMonth, $foodCategory, '1500.00', 'EUR');
        $this->addBudgetLine($previousMonth, $housingCategory, '1500.00', 'EUR');
        $this->addBudgetLine($previousMonth, $transportCategory, '220.00', 'EUR');
        $this->addBudgetLine($previousMonth, $shoppingCategory, '800.00', 'EUR');
        $this->addBudgetLine($previousMonth, $healthCategory, '200.00', 'EUR');
        $this->addBudgetLine($previousMonth, $otherExpenseCategory, '280.00', 'EUR');
        // Planned salary close to actual UAH salary in EUR (~€3 170) to avoid income shortfall.
        $this->addBudgetLine($previousMonth, $salaryCategory, '3300.00', 'EUR');
        $manager->persist($previousMonth);

        // ── Two months ago: another completed A budget ──────────────────────────
        $twoMonthsAgoStart = $now->subMonths(2)->startOfMonth();
        $twoMonthsAgoEnd = $now->subMonths(2)->endOfMonth();

        $twoMonthsAgo = new Budget();
        $twoMonthsAgo->setOwner($owner);
        $twoMonthsAgo
            ->setPeriodType(Budget::PERIOD_MONTHLY)
            ->setStartDate($twoMonthsAgoStart)
            ->setEndDate($twoMonthsAgoEnd)
            ->setName(null);

        $this->addBudgetLine($twoMonthsAgo, $foodCategory, '1450.00', 'EUR');
        $this->addBudgetLine($twoMonthsAgo, $housingCategory, '1500.00', 'EUR');
        $this->addBudgetLine($twoMonthsAgo, $transportCategory, '200.00', 'EUR');
        $this->addBudgetLine($twoMonthsAgo, $shoppingCategory, '750.00', 'EUR');
        $this->addBudgetLine($twoMonthsAgo, $healthCategory, '180.00', 'EUR');
        $this->addBudgetLine($twoMonthsAgo, $salaryCategory, '3300.00', 'EUR');
        $manager->persist($twoMonthsAgo);

        // ── Yearly budget ───────────────────────────────────────────────────────
        $yearBudget = new Budget();
        $yearBudget->setOwner($owner);
        $yearBudget
            ->setPeriodType(Budget::PERIOD_YEARLY)
            ->setStartDate($now->startOfYear())
            ->setEndDate($now->endOfYear())
            ->setName($now->format('Y') . ' Annual Plan');

        // Annual totals set above the ~€39 600/year typical actual (€3 300 × 12).
        // Income planned at ~€40 000 (salary ~€3 170/month × 12 ≈ €38 040 + bonuses).
        $this->addBudgetLine($yearBudget, $foodCategory, '17000.00', 'EUR', 'All food & drinks');
        $this->addBudgetLine($yearBudget, $housingCategory, '18000.00', 'EUR', 'All housing costs');
        $this->addBudgetLine($yearBudget, $transportCategory, '2600.00', 'EUR');
        $this->addBudgetLine($yearBudget, $shoppingCategory, '9000.00', 'EUR');
        $this->addBudgetLine($yearBudget, $healthCategory, '2200.00', 'EUR');
        $this->addBudgetLine($yearBudget, $otherExpenseCategory, '3200.00', 'EUR');
        $this->addBudgetLine($yearBudget, $salaryCategory, '39600.00', 'EUR', 'Monthly salary × 12');
        $this->addBudgetLine($yearBudget, $bonusCategory, '3000.00', 'EUR', 'Expected quarterly bonuses');
        $manager->persist($yearBudget);

        // ── Custom Q1 multi-currency budget ─────────────────────────────────────
        $customQuarter = new Budget();
        $customQuarter->setOwner($owner);
        $customQuarter
            ->setPeriodType(Budget::PERIOD_CUSTOM)
            ->setStartDate($now->startOfYear())
            ->setEndDate($now->startOfYear()->addMonths(3)->subDay())
            ->setName('Q1 ' . $now->format('Y'));

        // Q1 plan: root categories cover all subcategory spending; income close to actual.
        $this->addBudgetLine($customQuarter, $foodCategory, '4200.00', 'EUR', 'Q1 food & drinks');
        $this->addBudgetLine($customQuarter, $housingCategory, '4500.00', 'EUR', 'Q1 housing');
        $this->addBudgetLine($customQuarter, $transportCategory, '660.00', 'EUR');
        $this->addBudgetLine($customQuarter, $shoppingCategory, '2400.00', 'EUR');
        $this->addBudgetLine($customQuarter, $healthCategory, '540.00', 'EUR');
        $this->addBudgetLine($customQuarter, $otherExpenseCategory, '900.00', 'EUR');
        $this->addBudgetLine($customQuarter, $salaryCategory, '9900.00', 'EUR', 'Q1 salary');
        $this->addBudgetLine($customQuarter, $rentIncomeCategory, '18000.00', 'UAH', 'Rental income in UAH');
        $manager->persist($customQuarter);

        // ── Empty budget (edge case) ────────────────────────────────────────────
        $emptyBudget = new Budget();
        $emptyBudget->setOwner($owner);
        $emptyBudget
            ->setPeriodType(Budget::PERIOD_MONTHLY)
            ->setStartDate($now->subMonths(6)->startOfMonth())
            ->setEndDate($now->subMonths(6)->endOfMonth())
            ->setName('Empty Draft');
        $manager->persist($emptyBudget);

        $manager->flush();
    }

    private function addBudgetLine(
        Budget $budget,
        ?Category $category,
        string $amount,
        string $currency,
        ?string $note = null,
    ): void {
        if (!$category instanceof Category) {
            return;
        }

        $line = new BudgetLine();
        $line->setCategory($category);
        $line->setPlannedAmount($amount);
        $line->setPlannedCurrency($currency);
        $line->setNote($note);
        $budget->addLine($line);
    }

    public function getDependencies(): array
    {
        return [
            UserFixtures::class,
            ExpenseCategoryFixtures::class,
            IncomeCategoryFixtures::class,
        ];
    }
}
